// <auto-generated />
using System;
using Crescer.Booking.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Crescer.Booking.Infra.Migrations
{
    [DbContext(typeof(BookingContext))]
    [Migration("20180611163226_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Crescer.Booking.Dominio.Entidades.Opcional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<decimal?>("Valor")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Opcional");
                });

            modelBuilder.Entity("Crescer.Booking.Dominio.Entidades.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DataFim")
                        .IsRequired();

                    b.Property<DateTime?>("DataInicio")
                        .IsRequired();

                    b.Property<int?>("NumeroPessoas")
                        .IsRequired();

                    b.Property<int>("SuiteId");

                    b.Property<int>("UsuarioId");

                    b.Property<decimal?>("subTotal");

                    b.Property<decimal?>("valorTotal");

                    b.HasKey("Id");

                    b.HasIndex("SuiteId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Reserva");
                });

            modelBuilder.Entity("Crescer.Booking.Dominio.Entidades.ReservaOpcional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("OpcionalId")
                        .IsRequired();

                    b.Property<int?>("ReservaId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("OpcionalId");

                    b.HasIndex("ReservaId");

                    b.ToTable("ReservaOpcional");
                });

            modelBuilder.Entity("Crescer.Booking.Dominio.Entidades.Suite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Capacidade")
                        .IsRequired();

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<decimal?>("ValorDiaria")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Suite");
                });

            modelBuilder.Entity("Crescer.Booking.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<DateTime?>("DataNascimento")
                        .IsRequired();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("PrimeiroNome")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("UltimoNome")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Crescer.Booking.Dominio.Entidades.Reserva", b =>
                {
                    b.HasOne("Crescer.Booking.Dominio.Entidades.Suite", "Suite")
                        .WithMany()
                        .HasForeignKey("SuiteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Crescer.Booking.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Crescer.Booking.Dominio.Entidades.ReservaOpcional", b =>
                {
                    b.HasOne("Crescer.Booking.Dominio.Entidades.Opcional", "Opcional")
                        .WithMany()
                        .HasForeignKey("OpcionalId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Crescer.Booking.Dominio.Entidades.Reserva", "Reserva")
                        .WithMany()
                        .HasForeignKey("ReservaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
