// <auto-generated />
using System;
using Crescer.Spotify.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Crescer.Spotify.Infra.Migrations
{
    [DbContext(typeof(SpotifyContext))]
    [Migration("20180604202759_InicialMigration")]
    partial class InicialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Crescer.Spotify.Dominio.Entidades.Album", b =>
                {
                    b.Property<int>("IdAlbum")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("IdAlbum");

                    b.ToTable("Album");
                });

            modelBuilder.Entity("Crescer.Spotify.Dominio.Entidades.Avaliacao", b =>
                {
                    b.Property<int>("IdAvaliacao")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MusicaIdMusica")
                        .IsRequired();

                    b.Property<int>("Nota");

                    b.Property<int?>("UsuarioIdUsuario")
                        .IsRequired();

                    b.HasKey("IdAvaliacao");

                    b.HasIndex("MusicaIdMusica");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("Avaliacao");
                });

            modelBuilder.Entity("Crescer.Spotify.Dominio.Entidades.Musica", b =>
                {
                    b.Property<int>("IdMusica")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AlbumIdAlbum")
                        .IsRequired();

                    b.Property<double>("Duracao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("IdMusica");

                    b.HasIndex("AlbumIdAlbum");

                    b.ToTable("Musica");
                });

            modelBuilder.Entity("Crescer.Spotify.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .HasMaxLength(20);

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Crescer.Spotify.Dominio.Entidades.Avaliacao", b =>
                {
                    b.HasOne("Crescer.Spotify.Dominio.Entidades.Musica", "Musica")
                        .WithMany()
                        .HasForeignKey("MusicaIdMusica")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Crescer.Spotify.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Crescer.Spotify.Dominio.Entidades.Musica", b =>
                {
                    b.HasOne("Crescer.Spotify.Dominio.Entidades.Album", "Album")
                        .WithMany()
                        .HasForeignKey("AlbumIdAlbum")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
